**Welcome to numpy tutorial*


In [7]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/14.8 MB 2.0 MB/s eta 0:00:08
      --------------------------------------- 0.2/14.8 MB 3.1 MB/s eta 0:00:05
     - -------------------------------------- 0.4/14.8 MB 3.2 MB/s eta 0:00:05
     - -------------------------------------- 0.7/14.8 MB 4.2 MB/s eta 0:00:04
     -- ------------------------------------- 0.7/14.8 MB 3.9 MB/s eta 0:00:04
     -- ------------------------------------- 0.8/14.8 MB 3.2 MB/s eta 0:00:05
     -- ------------------------------------- 0.8/14.8 MB 3.2 MB/s eta 0:00:05
     --- ------------------------------------ 1.2/14.8 MB 3.3 MB/s eta 0:00:05
     --- ------------------------------------ 1.3/14.8 MB 3.3 MB/s eta 0:00:05
     --- ------------------------------------ 1.4/14.8 MB 3.0 MB/s eta 0:00:05
     ---- ----------------------------------- 1.5/14.8 MB 2.9 MB/s eta 0:00:05
     ---- ----------------------------------- 1.7/14.8 MB 3


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
myarr = np.array([1,2,3,4,5,6,7])

In [5]:
myarr

array([1, 2, 3, 4, 5, 6, 7])

If we have to give intiger of 8 bit then it will give as , if no is greater than we can give as 64, 32, float 64 etc.

In [26]:
myarr = np.array([[1,2,3,4,58,6,7]], np.int8)  # now it is two dimensional array

In [27]:
myarr

array([[ 1,  2,  3,  4, 58,  6,  7]], dtype=int8)

In [28]:
myarr.shape

(1, 7)

In [29]:
myarr[0, 3]

4

In [30]:
myarr.dtype

dtype('int8')

In [31]:
# we can change the elements of array 

In [32]:
myarr[0,2]=34

In [33]:
myarr

array([[ 1,  2, 34,  4, 58,  6,  7]], dtype=int8)

In [34]:
# there are 5 ways to create numpy array

In [35]:
# upper is , how we can create numpy array by using python object - list

# array creation :  conversion from other python structures

In [38]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [39]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
listarray.dtype

dtype('int32')

In [42]:
listarray.shape


(3, 3)

In [43]:
listarray.size

9

In [46]:
np.array({'a' : 'mango', 'b': 'apple'}) # this is one of the dictonary

array({'a': 'mango', 'b': 'apple'}, dtype=object)

In [50]:
zeros = np.zeros((3,4))   # it will fill with zero of passing 

In [51]:
zeros.dtype

dtype('float64')

In [52]:
zeros.shape

(3, 4)

In [53]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
rng = np.arange(4)

In [58]:
rng

array([0, 1, 2, 3])

In [61]:
lspace = np.linspace(1,50,10) # it will give equal spacing in given input it means in 10 parts it will give 1 to 59 numbers with equal space

In [62]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [65]:
space = np.linspace(1,4,4) # it will divide 1 to 4 in 4 equal parts 

In [66]:
space

array([1., 2., 3., 4.])

In [92]:
em = np.empty((2,2))  # it will give an empty array 

In [93]:
em

array([[1., 2.],
       [3., 4.]])

In [94]:
em.shape

(2, 2)

In [72]:
# there is one more function like empty i.e emptylike

In [76]:
em_like = np.empty_like(space)    # for what , it is for when we can any time element in any space of that empty array 

In [77]:
em_like

array([1., 2., 3., 4.])

In [78]:
ide = np.identity(45)

In [82]:
ide   # it is use for identity matrice for alzebra purpose

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [83]:
ide.shape

(45, 45)

In [84]:
ide.dtype

dtype('float64')

In [85]:
arr = np.arange(50)

In [86]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [89]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [91]:
arr.ravel()   # it will become the 1 d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

 Now we are talking about axis :
 
 if it is one dimension array then there is 0 axis 
       e.g. [1,2,3,4,5,6]
       
 it it is two dimensional array then there are two axis i.e. 0 and 1
        e.g.[1 2 3]
            [4 5 6]
            [7 8 9]
            
            if we sum verticaly means sum of axis 0 then it will give [12 15 18]
            after we can sum horizontly means of axis 1 then it will give [6 15 24]
            
            
            axis 0 goes to row ki taraf 
            axis 1 goes to coloum ki taraf
            
            
            
            now we directly go on example with same 
            

In [95]:
x = [[1,2,3], [4,5,6], [7,8,9]]

In [96]:
ar = np.array(x)

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
ar.sum(axis = 0)

array([12, 15, 18])

In [99]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [100]:
# now we start for attributes and methods 

In [101]:
ar.T # transpose means row become coloum and viceversa

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [103]:
ar.flat  # it is one iterable for that we should use for loop

In [105]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [110]:
ar.ndim  # it will give the dimension 

2

In [112]:
ar.size  # it will how much items hai

9

In [114]:
ar.nbytes  # how much bytes comsume in array it will show 

36

In [115]:
one = np.array([1,2,3,4,555,666,777])

In [116]:
one

array([  1,   2,   3,   4, 555, 666, 777])

In [118]:
one.argmax()   # it will show the on what index maxium means larger no is present

6

In [119]:
one.argmin()

0

In [121]:
one.argsort()  # it will the index of from smaller number to larger no it means at 0 index smaller no is present and at 6 index larger no is present

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [122]:
# for 2 d array then 

In [123]:
ar 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
 ar.argmax()  # first it expand the array means it will keep in one line then 

8

In [125]:
ar.argmin()

0

In [126]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [127]:
ar.argmax(axis = 0) # it will go in axis zero means row wise i.e vertically then larger element 7 is on 2 index same as 8, 9

array([2, 2, 2], dtype=int64)

In [129]:
ar.argmax(axis = 1)  # it will go in axis one means coloum wise i.e horizontally then larger element is 3 is on 2 index same as 6 , 9

array([2, 2, 2], dtype=int64)

In [130]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [131]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [132]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
ar.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [134]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
ar2 = np.array([[2,5,6],[3,4,7],[1,2,4]])

In [137]:
ar2

array([[2, 5, 6],
       [3, 4, 7],
       [1, 2, 4]])

In [138]:
ar + ar2

array([[ 3,  7,  9],
       [ 7,  9, 13],
       [ 8, 10, 13]])

In [139]:
ar * ar2

array([[ 2, 10, 18],
       [12, 20, 42],
       [ 7, 16, 36]])

In [141]:
np.sqrt(ar2)   # it will make the square root of given elements

array([[1.41421356, 2.23606798, 2.44948974],
       [1.73205081, 2.        , 2.64575131],
       [1.        , 1.41421356, 2.        ]])

In [143]:
ar2.max()

7

In [144]:
ar2.min()

1

In [145]:
ar2.sum()

34

In [146]:
ar2

array([[2, 5, 6],
       [3, 4, 7],
       [1, 2, 4]])

In [149]:
wher = np.where(ar2 > 6)

In [150]:
wher 

(array([1], dtype=int64), array([2], dtype=int64))

In [151]:
type(wher)

tuple

In [153]:
np.count_nonzero(ar2)  # it will give the count of non zero no in array

9

In [ ]:
attributes and methods of numpy   scipy.org